apiVersion: apps/v1
kind: Deployment
metadata:
  name: luoo-muziko-7bb8c69889-gr8b5
  namespace: muziko
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-muziko-luoo-muziko
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2019-11-16T08:08:44Z"
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-muziko-luoo-muziko
    spec:
      containers:
        - image: registry.cn-shanghai.aliyuncs.com/loo/luo-muziko:${CICD_EXECUTION_ID}
          imagePullPolicy: Always
          name: luoo-muziko
          ports:
            - containerPort: 8081
              name: port-1
              protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: aliyun-dockerhub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

