server:
  port: 8081
spring:
  main:
    banner-mode: 'off'
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username: root
    password:
  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 500MB
  redis:
    host:
  activemq:
    pool:
      enabled: false
    broker-url:
    user:
    password:



## aliyun
aliyun:
  oss.bucketname:
  oss.endpoint:
  oss.accessKeyId:
  oss.accessKeySecret:
  accessKeyId:
  accessKeySecret:
  domain:
  product:



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl